# StaxRip2 does not currently publish project-specific funding links.

github:
patreon:
open_collective:
ko_fi:
buy_me_a_coffee:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom: []
